ALTER TABLE "savedroutine"
	DROP COLUMN IF EXISTS "createdAt",
	DROP COLUMN IF EXISTS "semester";

ALTER TABLE "savedroutine"
	ADD COLUMN IF NOT EXISTS createdAt BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
	ADD COLUMN IF NOT EXISTS semester TEXT NOT NULL;
